<a href="https://colab.research.google.com/github/sunnyna/TIL/blob/master/1501_%EB%82%98%EC%84%9C%EC%97%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. 두문서의 TDM으로 생성하는 코드를 작성하시오.

In [ ]:
docs = ['우리반은 마라탕을 좋아해', '우리반은 마라탕을 더 이상 먹지 않을거야. 그래도 마라탕을 좋아해']

In [ ]:
# 토큰화

docs_ls = [doc.split() for doc in docs]

docs_ls


[['우리반은', '마라탕을', '좋아해'],
 ['우리반은', '마라탕을', '더', '이상', '먹지', '않을거야.', '그래도', '마라탕을', '좋아해']]

In [ ]:
# 인덱스 지정
from collections import defaultdict

word2idx = defaultdict(lambda : len(word2idx))

[word2idx[token] for doc in docs_ls for token in doc]

word2idx

defaultdict(<function __main__.<lambda>>,
            {'그래도': 7,
             '더': 3,
             '마라탕을': 1,
             '먹지': 5,
             '않을거야.': 6,
             '우리반은': 0,
             '이상': 4,
             '좋아해': 2})

In [ ]:
import numpy as np

TDM =  np.zeros((len(word2idx),len(docs_ls)), dtype = int)

for i, doc in enumerate(docs_ls):
  for token in doc:
    TDM[word2idx[token], i] += 1

TDM

array([[1, 1],
       [1, 2],
       [1, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1]])

2. TF - IDF를 계산하시오.

In [ ]:
DTM = TDM.transpose()

DTM

array([[1, 1, 1, 0, 0, 0, 0, 0],
       [1, 2, 1, 1, 1, 1, 1, 1]])

In [ ]:

def computeTF(DTM):
  docs_len = len(DTM)
  word_len = len(DTM[0])

  tf = np.zeros((docs_len, word_len))

  for docs_i in range(docs_len):
    for word_i in range(word_len):
      tf[docs_i, word_i] = (DTM[docs_i, word_i])/DTM[docs_i].sum()

  return tf

computeTF(DTM)

array([[0.33333333, 0.33333333, 0.33333333, 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.11111111, 0.22222222, 0.11111111, 0.11111111, 0.11111111,
        0.11111111, 0.11111111, 0.11111111]])

In [ ]:
import math

def computeIDF(DTM):
  docs_len = len(DTM)
  word_len = len(DTM[0])

  idf = np.zeros((word_len))

  for i in range(word_len):
    idf[i] = -math.log10(np.count_nonzero(DTM[:,i])/docs_len)

  return idf

computeIDF(DTM)

array([-0.     , -0.     , -0.     ,  0.30103,  0.30103,  0.30103,
        0.30103,  0.30103])

3. 자카드유사도

In [ ]:
def jaccad_sim(x,y):
  x= x.split()
  y= y.split()

  intersection = set(x).intersection(set(y))
  union = set(x).union(set(y))

  return len(intersection)/ len(union)

jaccad_sim(docs[0], docs[1])


0.375

4. 나이브베이즈 분류기

In [ ]:
import math
log_prob1 += math.log(prob1)
log_prob1 += math.log(prob0) 

log_prob0 += math.log(doccnnt0/(doccnt0+doccnt1))
log_prob1 += math.log(doccont1/(doccnt0+doccnt1))

prob0 = math.exp(log_prob0)
prob1 = math.exp(log_prob1) 