<a href="https://colab.research.google.com/github/sunnyna/TIL/blob/master/testpractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TDM 계산

In [19]:
docs = ['오늘 동물원에서 원숭이를 봤어',
        '오늘 동물원에서 코끼리를 봤어 봤어',
        '동물원에서 원숭이에게 바나나를 줬어 바나나를']

In [57]:
# 띄어쓰기 단위로 토큰화


In [58]:
# 인덱스 지정


defaultdict(<function __main__.<lambda>>,
            {'동물원에서': 1,
             '바나나를': 6,
             '봤어': 3,
             '오늘': 0,
             '원숭이를': 2,
             '원숭이에게': 5,
             '줬어': 7,
             '코끼리를': 4})

In [62]:
# TDM 구하기


array([[1, 1, 0],
       [1, 1, 1],
       [1, 0, 0],
       [1, 2, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 2],
       [0, 0, 1]])

In [70]:
# dataframe 생성



문서0  문서1  문서2
단어                  
동물원에서    1    1    0
바나나를     1    1    1
봤어       1    0    0
오늘       1    2    0
원숭이를     0    1    0
원숭이에게    0    0    1
줬어       0    0    2
코끼리를     0    0    1

In [20]:
# 띄어쓰기 단위로 토큰화

docs_token = [doc.split() for doc in docs]

docs_token

[['오늘', '동물원에서', '원숭이를', '봤어'],
 ['오늘', '동물원에서', '코끼리를', '봤어', '봤어'],
 ['동물원에서', '원숭이에게', '바나나를', '줬어', '바나나를']]

In [22]:
# 인덱스 지정
from collections import defaultdict

word2id = defaultdict(lambda: len(word2id))

[word2id[token] for doc in docs_token for token in doc]
word2id

defaultdict(<function __main__.<lambda>>,
            {'동물원에서': 1,
             '바나나를': 6,
             '봤어': 3,
             '오늘': 0,
             '원숭이를': 2,
             '원숭이에게': 5,
             '줬어': 7,
             '코끼리를': 4})

In [32]:
# TDM 생성
import numpy as np

TDM = np.zeros((len(word2id),len(docs_token)),dtype= int)

for i, doc in enumerate(docs_token):
  for token in doc:
    TDM[word2id[token],i] +=1

TDM

array([[1, 1, 0],
       [1, 1, 1],
       [1, 0, 0],
       [1, 2, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 2],
       [0, 0, 1]])

In [44]:
import pandas as pd

doc_names = ['문서' + str(i) for i in range(len(docs_token))]
sorted_vocab = sorted((key, value)for key, value in word2id.items())

vocab = [v[0] for v in sorted_vocab]

df = pd.DataFrame(TDM, columns=doc_names)

df['단어'] = vocab
df.set_index('단어')


문서0  문서1  문서2
단어                  
동물원에서    1    1    0
바나나를     1    1    1
봤어       1    0    0
오늘       1    2    0
원숭이를     0    1    0
원숭이에게    0    0    1
줬어       0    0    2
코끼리를     0    0    1

# TF-IDF

In [ ]:
docs = ['오늘 동물원에서 원숭이를 봤어',
        '오늘 동물원에서 코끼리를 봤어 봤어',
        '동물원에서 원숭이에게 바나나를 줬어 바나나를']

In [71]:
# 띄어쓰기 단위로 토큰화

docs_ls = [doc.split() for doc in docs]

docs_ls

[['오늘', '동물원에서', '원숭이를', '봤어'],
 ['오늘', '동물원에서', '코끼리를', '봤어', '봤어'],
 ['동물원에서', '원숭이에게', '바나나를', '줬어', '바나나를']]

In [74]:
# 인덱스 지정
from collections import defaultdict

word2id = defaultdict(lambda : len(word2id))

[word2id[token] for doc in docs_ls for token in doc]

word2id

defaultdict(<function __main__.<lambda>>,
            {'동물원에서': 1,
             '바나나를': 6,
             '봤어': 3,
             '오늘': 0,
             '원숭이를': 2,
             '원숭이에게': 5,
             '줬어': 7,
             '코끼리를': 4})

In [75]:
# DTM 계산

DTM = TDM.transpose()

DTM

array([[1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 0, 2, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 2, 1]])

# 유사도

In [ ]:
word_embedding_dic = { '사과' : [1.0, 0.5], '바나나' : [0.9, 1.2], '원숭이' : [0.5, 1.5] }

In [ ]:
# 유클리디안 유사도
import numpy as np

def euclidean_sim(x,y):
  x= np.array(x)
  y= np.array(y)

  return np.sqrt(np.sum(x-y)**2)

euclidean_sim(word_embedding_dic['사과'],word_embedding_dic['바나나'])

0.6

In [ ]:
# 코사인 유사도
import numpy as np
from numpy import dot
from numpy.linalg import norm

def cosine_sim(x,y) :

  return dot(x,y)/(norm(x)*norm(y))

cosine_sim(word_embedding_dic['사과'],word_embedding_dic['바나나'])

0.8944271909999159

In [14]:
# 자카드 유사도

s1 = '대부분 원숭이는 바나나를 좋아합니다.'
s2 = '코주부 원숭이는 바나나를 싫어합니다.'

In [17]:
# 토큰화
s1_t = s1.split()
s2_t = s2.split()


intersection = set(s1_t).intersection(set(s2_t)) 
union = set(s1_t).union(set(s2_t))

jaccad_sim = len(intersection)/ len(union)

jaccad_sim

0.3333333333333333

# Naive Baysian