<a href="https://colab.research.google.com/github/sunnyna/TIL/blob/master/testpractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TDM 계산

In [19]:
docs = ['오늘 동물원에서 원숭이를 봤어',
        '오늘 동물원에서 코끼리를 봤어 봤어',
        '동물원에서 원숭이에게 바나나를 줬어 바나나를']

In [86]:
# 띄어쓰기 단위로 토큰화

doc_ls = [doc.split() for doc in docs]



[['오늘', '동물원에서', '원숭이를', '봤어'],
 ['오늘', '동물원에서', '코끼리를', '봤어', '봤어'],
 ['동물원에서', '원숭이에게', '바나나를', '줬어', '바나나를']]

In [95]:
# 인덱스 지정
from collections import defaultdict

word2id = defaultdict(lambda : len(word2id))

[word2id[token] for doc in docs_ls for token in doc]



7

In [89]:
# TDM 구하기
import numpy as np

TDM = np.zeros((len(word2id),len(doc_ls)), dtype= int)

for i, doc in enumerate(doc_ls):
  for token in doc:
    TDM[word2id[token],i] +=1

TDM

array([[1, 1, 0],
       [1, 1, 1],
       [1, 0, 0],
       [1, 2, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 2],
       [0, 0, 1]])

In [96]:
# 띄어쓰기 단위로 토큰화


[['오늘', '동물원에서', '원숭이를', '봤어'],
 ['오늘', '동물원에서', '코끼리를', '봤어', '봤어'],
 ['동물원에서', '원숭이에게', '바나나를', '줬어', '바나나를']]

In [97]:
# 인덱스 지정


defaultdict(<function __main__.<lambda>>,
            {'동물원에서': 1,
             '바나나를': 6,
             '봤어': 3,
             '오늘': 0,
             '원숭이를': 2,
             '원숭이에게': 5,
             '줬어': 7,
             '코끼리를': 4})

In [99]:
# TDM 생성


array([[1, 1, 0],
       [1, 1, 1],
       [1, 0, 0],
       [1, 2, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 2],
       [0, 0, 1]])

# TF-IDF

In [100]:
docs = ['오늘 동물원에서 원숭이를 봤어',
        '오늘 동물원에서 코끼리를 봤어 봤어',
        '동물원에서 원숭이에게 바나나를 줬어 바나나를']

In [101]:
# 띄어쓰기 단위로 토큰화

docs_ls = [doc.split() for doc in docs]


In [104]:
# 인덱스 지정
from collections import defaultdict

word2id = defaultdict(lambda: len(word2id))

[word2id[token] for doc in doc_ls for token in doc]

word2id

defaultdict(<function __main__.<lambda>>,
            {'동물원에서': 1,
             '바나나를': 6,
             '봤어': 3,
             '오늘': 0,
             '원숭이를': 2,
             '원숭이에게': 5,
             '줬어': 7,
             '코끼리를': 4})

In [105]:
# DTM 계산

DTM = TDM.transpose()

DTM

array([[1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 0, 2, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 2, 1]])

In [128]:
# TF 계산

def computeTF(DTM):
  doc_len = len(DTM)
  word_len = len(DTM[0])

  tf = np.zeros((doc_len, word_len))

  for doc_i in range(doc_len):
    for word_i in range(word_len):
      tf[doc_i, word_i] = DTM[doc_i, word_i]/ DTM[doc_i].sum()
  return tf


computeTF(DTM)

array([[0.25, 0.25, 0.25, 0.25, 0.  , 0.  , 0.  , 0.  ],
       [0.2 , 0.2 , 0.  , 0.4 , 0.2 , 0.  , 0.  , 0.  ],
       [0.  , 0.2 , 0.  , 0.  , 0.  , 0.2 , 0.4 , 0.2 ]])

In [132]:
# idf 계산 
import math

def compute_idf(DTM):
  doc_len = len(DTM)
  word_len = len(DTM[0])

  idf = np.zeros(word_len)

  for i in range(word_len):
    idf[i] = - math.log10(np.count_nonzero(DTM[:,i])/doc_len)
  return idf

compute_idf(DTM) 

array([ 0.17609126, -0.        ,  0.47712125,  0.17609126,  0.47712125,
        0.47712125,  0.47712125,  0.47712125])

In [71]:
# 띄어쓰기 단위로 토큰화

docs_ls = [doc.split() for doc in docs]

docs_ls

[['오늘', '동물원에서', '원숭이를', '봤어'],
 ['오늘', '동물원에서', '코끼리를', '봤어', '봤어'],
 ['동물원에서', '원숭이에게', '바나나를', '줬어', '바나나를']]

In [74]:
# 인덱스 지정
from collections import defaultdict

word2id = defaultdict(lambda : len(word2id))

[word2id[token] for doc in docs_ls for token in doc]

word2id

defaultdict(<function __main__.<lambda>>,
            {'동물원에서': 1,
             '바나나를': 6,
             '봤어': 3,
             '오늘': 0,
             '원숭이를': 2,
             '원숭이에게': 5,
             '줬어': 7,
             '코끼리를': 4})

In [75]:
# DTM 계산

DTM = TDM.transpose()

DTM

array([[1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 0, 2, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 2, 1]])

In [79]:
# TF 계산
# 문서내 토큰 빈도/ 문서내 전체 토큰빈도

def computeTF(DTM):
  doc_len = len(DTM)
  word_len = len(DTM[0])

  tf = np.zeros((doc_len, word_len))

  for doc_i in range(doc_len):
    for word_i in range(word_len):
      tf[doc_i, word_i] = DTM[doc_i,word_i] / DTM[doc_i].sum()
  return tf

computeTF(DTM)

array([[0.25, 0.25, 0.25, 0.25, 0.  , 0.  , 0.  , 0.  ],
       [0.2 , 0.2 , 0.  , 0.4 , 0.2 , 0.  , 0.  , 0.  ],
       [0.  , 0.2 , 0.  , 0.  , 0.  , 0.2 , 0.4 , 0.2 ]])

In [85]:
# idf 계산 
# IDF = log(총문서수/토큰이등장한문서수)
import math


def computeIDF(DTM):
  doc_len = len(DTM)
  word_len = len(DTM[0])

  idf = np.zeros(word_len)

  for i in range(word_len):
    idf[i] = - math.log10(np.count_nonzero(DTM[:,i])/ doc_len)

  return idf

computeIDF(DTM)


array([ 0.17609126, -0.        ,  0.47712125,  0.17609126,  0.47712125,
        0.47712125,  0.47712125,  0.47712125])

# 유사도

In [ ]:
word_embedding_dic = { '사과' : [1.0, 0.5], '바나나' : [0.9, 1.2], '원숭이' : [0.5, 1.5] }

In [107]:
# 유클리디안 유사도
import numpy as np
def euclidean_sim(x,y):
  x= np.array(x)
  y= np.array(y)

  return np.sqrt(np.sum(x-y)**2)

euclidean_sim(word_embedding_dic['사과'],word_embedding_dic['바나나'])

0.6

In [108]:
# 코사인 유사도
from numpy import dot
from numpy.linalg import norm

def cosine_sim(x,y):
  
  return dot(x,y)/(norm(x)*norm(y))

cosine_sim(word_embedding_dic['사과'],word_embedding_dic['바나나'])



0.8944271909999159

In [ ]:
# 자카드 유사도
s1 = '대부분 원숭이는 바나나를 좋아합니다.'
s2 = '코주부 원숭이는 바나나를 싫어합니다.'


In [110]:
s1_t = s1.split()
s2_t = s2.split()

intersection = set(s1_t).intersection(set(s2_t))
union = set(s1_t).union(set(s2_t))

jaccad_sim = len(intersection)/ len(union)
jaccad_sim

0.3333333333333333

In [ ]:
# 유클리디안 유사도
import numpy as np

def euclidean_sim(x,y):
  x= np.array(x)
  y= np.array(y)

  return np.sqrt(np.sum(x-y)**2)

euclidean_sim(word_embedding_dic['사과'],word_embedding_dic['바나나'])

0.6

In [ ]:
# 코사인 유사도
import numpy as np
from numpy import dot
from numpy.linalg import norm

def cosine_sim(x,y) :

  return dot(x,y)/(norm(x)*norm(y))

cosine_sim(word_embedding_dic['사과'],word_embedding_dic['바나나'])

0.8944271909999159

In [14]:
# 자카드 유사도

s1 = '대부분 원숭이는 바나나를 좋아합니다.'
s2 = '코주부 원숭이는 바나나를 싫어합니다.'

In [17]:
# 토큰화
s1_t = s1.split()
s2_t = s2.split()


intersection = set(s1_t).intersection(set(s2_t)) 
union = set(s1_t).union(set(s2_t))

jaccad_sim = len(intersection)/ len(union)

jaccad_sim

0.3333333333333333

# Naive Baysian

In [ ]:
training_set = [['me free lottery', 1],
 ['free get free you', 1],
 ['you free scholarship', 0],
 ['free to contact me', 0],
 ['you won award', 0],
 ['you ticket lottery', 1]]

In [ ]:
from collections import defaultdict

# 범주에 속하는 토큰수 세기 1(스팸), 0(정상))
doccnt0 = 0
doccnt1 = 0

# 토큰별로 문서내 빈도수 카운팅
wordfreq = defaultdict(lambda : [0, 0])

for doc, label in training_set:
  words = doc.split()
  for word in words:
    wordfreq[word][label] += 1

for key, (cnt0, cnt1) in wordfreq.items():
  doccnt0 += cnt0
  doccnt1 += cnt1

print('doccnt0 : {}'.format(doccnt0))
print('doccnt1 : {}'.format(doccnt1))

In [ ]:
# 토큰별 조건부 확률 계산
k = 0.5

wordprobs = defaultdict(lambda : [0, 0])
for key, (cnt0, cnt1) in wordfreq.items():
  wordprobs[key][0] = (cnt0 + k) /(2 * k + doccnt0)
  wordprobs[key][1] = (cnt1 + k) /(2 * k + doccnt1)

wordprobs

In [ ]:
# Classify : 신규 텍스트가 주어졌을 때 확률 계산

In [ ]:
import math

doc = "free lottery"
tokens = doc.split()

log_prob1 = log_prob0 = 0.0

for word, (prob0, prob1) in wordprobs.items():
  if word in tokens:
    log_prob0 += math.log(prob0) 
    log_prob1 += math.log(prob1)

log_prob0 += math.log(doccnt0/(doccnt0 + doccnt1))
log_prob1 += math.log(doccnt1/(doccnt0 + doccnt1))

prob0 = math.exp(log_prob0)
prob1 = math.exp(log_prob1)

print(prob0)
print(prob1)

print("정상확률 : {}".format( prob0 /(prob0 + prob1) * 100))
print("스팸확률 : {}".format( prob1 /(prob0 + prob1) * 100))